# Generated by Django 4.2.4 on 2023-08-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_task_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to=None,
        ),
    ]
