# Generated by Django 4.2.4 on 2023-08-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_alter_task_options_alter_task_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated', 'created']},
        ),
    ]
